from  selenium import webdriver
driver=webdriver.Chrome()
driver.get("https://www.google.com/")
driver.maximize_window()
driver.implicitly_wait(5)
print ("Title is:-",driver.title)
driver.get("https://www.facebook.com/")
print("Title is:-",driver.title)
driver.back()
print ("Title is:-",driver.title)
driver.forward()
print ("Title is:-",driver.title)
driver.back()
print ("Title is:-",driver.title)
